name = "PatchSensei"
client_id = "3644fd6661f8c864eb08f9fa454d45b9"
application_url = "https://d14rzh04nceswa.cloudfront.net"
embedded = true

[access_scopes]
scopes = "read_orders,write_orders,read_customers,read_products,write_products"

[auth]
redirect_urls = [
  "https://d14rzh04nceswa.cloudfront.net/auth/callback",
  "https://d14rzh04nceswa.cloudfront.net/auth/shopify/callback",
  "https://d14rzh04nceswa.cloudfront.net/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks/orders/updated"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
